name: Vite React Build with Bun

on:
  # Trigger the action on pushes to the main branch or on pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      
    - name: install and build
    - run : bun install
    - run : bun run build
         
    
    # Step 5: Upload built artifacts (Optional, if you want to use the build artifacts)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
